language: java

os: linux
dist: trusty
sudo: required
jdk: oraclejdk8
env: FAILURES_ALLOWED=false

# http://stackoverflow.com/questions/35128777/travis-ci-build-failed
before_install:
  - sudo apt-get update -qq
  - chmod +x gradlew

script:
  - ./gradlew clean buildJfxJarWithDep

before_cache:
  - rm -f  $HOME/.gradle/caches/*/*.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts*/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
