language: java

jdk: oraclejdk8

sudo: required

# http://stackoverflow.com/questions/35128777/travis-ci-build-failed
before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew check
  - ./gradlew build

branches:
  only:
    - master
    - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)
